aliyun:
  oss:
    endpoint: oss-ap-southeast-3.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI5tRBYBzy6MnpW25BJF63 # 访问身份验证中用到用户标识
    accessKeySecret: 6XNy1VxEkr2JnLPvZ03Ziv1QL2zeYy # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: bookshare-fyp # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    #callback:  # 文件上传成功后的回调地址
    dir:
      prefix: bookshare-fyp/ # 上传文件夹路径前缀