#生产环境配置
server:
  port: 8081

springdoc:
  api-docs:
    enabled: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  mail:
    host: smtp.gmail.com
    username: kfc16978.ww@gmail.com
    password: ayfluoxvpxoevzwt
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin
    virtual-host: /

  data:
    redis:
      host: redis
      port: 6379

  datasource:
    url: jdbc:mysql://mysql:3306/test
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

  security:
    jwt:
      key: 'abcdefghijklmn'
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100

  web:
    verify:
      mail-limit: 60
    flow:
      period: 3
      limit: 10
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'
